In [2]:
import tensorflow as tf

In [3]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [4]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [6]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [7]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [8]:
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 0.3516813   0.2682092   1.8351797 ]
 [-0.51331115  0.5924116   0.9716565 ]
 [-0.10373986 -0.34956014  0.348693  ]], shape=(3, 3), dtype=float32)


In [9]:
x = tf.random.uniform((3,3), minval=-1, maxval=1)
print(x)

tf.Tensor(
[[-0.5098424  -0.7576904   0.89262533]
 [ 0.84320855  0.32523394  0.01528525]
 [-0.91304874 -0.7084999   0.47746897]], shape=(3, 3), dtype=float32)


In [11]:
x = tf.range(start=1, limit=10, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [12]:
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [17]:
x = tf.constant([1,2,3])
y = tf.constant([7,8,9])

z = tf.add(x, y)
print(z)
z1 = x + y
print(f'z : {z}')
print(f'z1 : {z1}')

tf.Tensor([ 8 10 12], shape=(3,), dtype=int32)
z : [ 8 10 12]
z1 : [ 8 10 12]


In [18]:
z = tf.subtract(x, y)
print(z)
z1 = x - y
print(f'z : {z}')
print(f'z1 : {z1}')

tf.Tensor([-6 -6 -6], shape=(3,), dtype=int32)
z : [-6 -6 -6]
z1 : [-6 -6 -6]


In [19]:
z = tf.divide(x, y)
print(z)
z1 = x / y
print(f'z : {z}')
print(f'z1 : {z1}')

tf.Tensor([0.14285714 0.25       0.33333333], shape=(3,), dtype=float64)
z : [0.14285714 0.25       0.33333333]
z1 : [0.14285714 0.25       0.33333333]


In [20]:
z = tf.multiply(x, y)
print(z)
z1 = x * y
print(f'z : {z}')
print(f'z1 : {z1}')

tf.Tensor([ 7 16 27], shape=(3,), dtype=int32)
z : [ 7 16 27]
z1 : [ 7 16 27]


In [21]:
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(50, shape=(), dtype=int32)


In [24]:
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(50, shape=(), dtype=int32)


In [25]:
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [30]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = tf.matmul(x, y)
print(z)

z = x @ y
print(z)

tf.Tensor(
[[ 0.9799289   1.8445886   2.0703602   0.08418545]
 [ 0.1871345  -2.138809   -1.8794461  -0.8862495 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.9799289   1.8445886   2.0703602   0.08418545]
 [ 0.1871345  -2.138809   -1.8794461  -0.8862495 ]], shape=(2, 4), dtype=float32)


If you don't run the above code, add these two lines in front of the code, I'm working on colab so I don't need this code.

physical_devices = tf.config.list_physical_devices('GPU')

tf.config.experimental.set_memory_growth(physical_devices[0], True)



In [36]:
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [37]:
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [39]:
x = tf.constant([[1,2],
                [3,4],
                [5,6]])

print(x[0,:])
print(x[0:2,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [44]:
x = tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
# x = tf.reshape(x, (3,2)) it'll give an error, it makes 3x2 = 6 but our array is 9 in length
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [46]:
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
